### ISSUE TITLE
Fetching DisGeNET, neXtProt, and WikiPathways nanopublications fail

### ISSUE THREAD

**Issue by ImranAsif48** [fair-workflows/nanopub#134] opened 2021-04-28 12:28 UTC
I got the error while fetching the nanopublication of DisGeNET, neXtProt and WikiPathways. Please see the attache image for more information. 

![error](https://user-images.githubusercontent.com/52410211/116403559-9b700c00-a825-11eb-886c-515f2a215fba.png)

**Comment by raar1** [comment] 2021-04-30 12:10
Hi Imran, thanks very much for reporting this! We will look into it as soon as possible.

**Comment by svenvanderburg** [comment] 2021-08-02 07:54
@ImranAsif48 as soon as possible is not very soon as we are very busy at the moment, sorry!

**Comment by raar1** [comment] 2021-08-13 14:16
Hi @ImranAsif48, I'm looking into this now but I can't seem to access any of the nanopubs at the URIs in your script above. I used OCR to convert the image to text, so it's possible there was some mistake, but when I check it looks like the URIs are the same as above. Has something changed in the Manchester domain?

Would you be able to post a couple of URIs (that have this issue) that are working for you right now?

**Comment by ImranAsif48** [comment] 2021-08-14 13:33
Hi @raar1, Thanks for your reply back and for considering this issue. I checked with other nanopub servers, but still, I got the same error. I am sending you some example URIs that cause the issue.

- RA--7DLsdDz3gK0seVQSreUPLlnQzxT9xnNc9sjM6CnTU
- RAEvihrkmJntLWBr9FaarFVoFy57WGjU-_ymihVyDyXnM
- RATwhMUeIc7lBAXbYI8bbOArMBWSJPQQQjgoToSRyYYGw
- RAS4qPtiBLHtvwpegMMx_gYukMbcD3RED_SI9v8-eCScE

**Comment by raar1** [comment] 2021-08-17 15:50
Thank you @ImranAsif48. Yes, I see that the problem is `nanopub` currently expects subgraphs 'provenance', 'head', 'pubinfo' and  'assertion', whereas these other nanopubs have e.g. 'publicationinfo' or '__head' etc.

This is definitely a bug in `nanopub`, which should instead determine the names of the subgraphs based on triples in the head subgraph, e.g. `this: np:hasAssertion sub:assertion`. I will update the code to look for triples of that form, which should allow most (all?) such nanopubs to work with the library.

**Comment by vemonet** [comment] 2022-12-21 09:51
Hi @raar1 and @ImranAsif48 , I noticed this issue while working on implementing nanopub 2.0.0, and it is now fixed (normally). The nanopub lib now extract the graphs based on the `np:Nanopublication` in the head

It seems to work with all previously problematic nanopub, e.g.: `pip install "nanopub>=2.0.0"`

```python
from nanopub import Nanopub

np = Nanopub("http://purl.org/np/RAS4qPtiBLHtvwpegMMx_gYukMbcD3RED_SI9v8-eCScE")
print(np)
```

**Closed** 2023-03-27 08:42 UTC
Labels: bug
